#!/usr/bin/env python3
"""Encoding guard for the Pawn sources.

The SA-MP and open.mp compilers read `.inc` and `.pwn` files as plain bytes,
not as UTF-8: a non-ASCII byte is passed through to the AMX (or rejected)
instead of being decoded, so an accented letter or a typographic dash that
looks fine in an editor turns into mojibake -- or a compile error -- on the
server. A UTF-8 BOM is worse still: the compiler sees three stray bytes before
the first directive.

`include/mysql_samp.inc` and `include/mysql_samp_omp.inc` are generated by
`build.rs`, so anything that reaches them comes from the template
`include/mysql_samp.inc.in` -- all three are checked here, plus everything under
`examples/` and `benchmark/`, which users compile or feed to a server directly:
the `.pwn` scripts, but also `schema.sql`, `setup.sql` and `mysql.ini.example`,
which the plugin itself reads through `mysql_query_file` and
`mysql_connect_file`.

Markdown is the one exception. A `README.md` is rendered as UTF-8 by GitHub and
never reaches a Pawn compiler, so it is free to use real typography.

Run from the repository root:

    python3 .github/scripts/check_pawn_encoding.py

Exits 0 when every file is clean, 1 otherwise, printing one
`file:line:column: message` per problem.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

TEMPLATE = ROOT / "include/mysql_samp.inc.in"
GENERATED = ROOT / "include/mysql_samp.inc"
GENERATED_OMP = ROOT / "include/mysql_samp_omp.inc"

BOM = b"\xef\xbb\xbf"

# Tab and newline are legitimate; everything else below 0x20, plus DEL, is
# invisible in an editor and meaningless to the compiler.
ALLOWED_CONTROL = {0x09, 0x0A}


# Rendered as UTF-8 by GitHub and never fed to a Pawn compiler or a server.
EXEMPT_SUFFIXES = {".md"}


def pawn_sources() -> list[Path]:
    """Every file that must stay pure ASCII.

    Everything in `examples/` and `benchmark/` counts, not just the `.pwn`
    scripts: the listing is opt-out rather than opt-in, so a new `.sql` fixture
    or config sample is covered the day it is added, without touching this
    script.
    """
    files = [TEMPLATE, GENERATED, GENERATED_OMP]
    for directory in ("examples", "benchmark"):
        for path in sorted((ROOT / directory).rglob("*")):
            if path.is_file() and path.suffix not in EXEMPT_SUFFIXES:
                files.append(path)
    return files


def position(data: bytes, offset: int) -> tuple[int, int]:
    """Report line:column (1-based, counting bytes) for a byte offset."""
    line = data.count(b"\n", 0, offset) + 1
    line_start = data.rfind(b"\n", 0, offset) + 1
    return line, offset - line_start + 1


def check_file(path: Path, problems: list[str]) -> None:
    data = path.read_bytes()
    rel = path.relative_to(ROOT)

    if data.startswith(BOM):
        problems.append(
            f"{rel}:1:1: starts with a UTF-8 BOM. The Pawn compiler does not strip "
            f"it and will choke on the first directive."
        )

    for offset, byte in enumerate(data):
        if byte > 0x7F:
            line, column = position(data, offset)
            problems.append(
                f"{rel}:{line}:{column}: non-ASCII byte 0x{byte:02X}. The Pawn "
                f"compiler does not decode UTF-8; use plain ASCII (e.g. `-` "
                f"instead of an em dash, `\"` instead of curly quotes)."
            )
            break

    for offset, byte in enumerate(data):
        if (byte < 0x20 and byte not in ALLOWED_CONTROL) or byte == 0x7F:
            line, column = position(data, offset)
            problems.append(
                f"{rel}:{line}:{column}: stray control byte 0x{byte:02X}. Expected "
                f"LF line endings and no CR, NUL or other control characters."
            )
            break


def crate_version() -> str:
    """The `version` of the [package] section in Cargo.toml."""
    text = (ROOT / "Cargo.toml").read_text(encoding="utf-8")
    package = text.split("[package]", 1)[1]
    package = re.split(r"^\[", package, maxsplit=1, flags=re.MULTILINE)[0]
    match = re.search(r'^version\s*=\s*"([^"]+)"', package, flags=re.MULTILINE)
    if match is None:
        raise SystemExit("could not find the package version in Cargo.toml")
    return match.group(1)


def check_generated_is_current(problems: list[str]) -> None:
    """The guard is only meaningful if the generated file is current.

    A stale `.inc` could pass while the template it came from already
    regressed.
    """
    rendered = TEMPLATE.read_text(encoding="utf-8").replace("{{VERSION}}", crate_version())
    if rendered != GENERATED.read_text(encoding="utf-8"):
        problems.append(
            "include/mysql_samp.inc is out of date with include/mysql_samp.inc.in. "
            "Run `cargo build` to regenerate it."
        )


def main() -> int:
    problems: list[str] = []

    for path in pawn_sources():
        check_file(path, problems)
    check_generated_is_current(problems)

    if problems:
        for problem in problems:
            print(f"::error::{problem}" if sys.argv[1:2] == ["--github"] else problem)
        print(f"\n{len(problems)} problem(s) found.", file=sys.stderr)
        return 1

    print(f"OK: {len(pawn_sources())} Pawn source(s) are pure ASCII and up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
