[package]
name = "mysql_samp"
version = "1.1.0"
edition = "2024"
authors = ["NullSablex <https://github.com/NullSablex>"]
repository = "https://github.com/NullSablex/mysql_samp"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
samp = { git = "https://github.com/NullSablex/rust-samp.git", tag = "v3.0.0" }
mysql = { version = "28.0.0", default-features = false, features = ["default-rust"] }
chrono = "0.4"

[package.metadata.samp]
uid = "0x4e10002241c700f4"
