//! Encoding guard for the Pawn includes.
//!
//! The SA-MP and open.mp compilers read `.inc` files as plain bytes, not as
//! UTF-8: a non-ASCII byte is passed through to the AMX (or rejected) instead
//! of being decoded, so an accented letter or a typographic dash that looks
//! fine in an editor turns into mojibake — or a compile error — on the server.
//! A UTF-8 BOM is worse still: the compiler sees three stray bytes before the
//! first directive.
//!
//! `include/mysql_samp.inc` and `include/mysql_samp_omp.inc` are generated by
//! `build.rs` from `include/mysql_samp.inc.in`, so a regression enters through
//! the template and spreads to both. That is what makes this a Rust test: the
//! includes are build output of this crate, and `cargo build` is what produces
//! them.
//!
//! **Scope is deliberately the three includes and nothing else.** The
//! `examples/` and `benchmark/` files are checked by the CI job instead
//! (`.github/workflows/encoding.yml` → `.github/scripts/check_pawn_encoding.py`,
//! which covers those *and* these), so editing an example never depends on the
//! Rust suite — it is not build input, and a doc-only change has no business
//! failing a test binary. The CI script is the superset; keep a rule added here
//! in sync with it.

use std::fs;
use std::path::{Path, PathBuf};

/// The template and both generated includes, relative to the crate root.
fn includes() -> Vec<PathBuf> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    vec![
        root.join("include/mysql_samp.inc.in"),
        root.join("include/mysql_samp.inc"),
        root.join("include/mysql_samp_omp.inc"),
    ]
}

fn read(path: &Path) -> Vec<u8> {
    fs::read(path).unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
}

/// Reports `line:column` (1-based, counting bytes) for a byte offset.
fn position(bytes: &[u8], offset: usize) -> (usize, usize) {
    let line = bytes[..offset].iter().filter(|&&b| b == b'\n').count() + 1;
    let line_start = bytes[..offset]
        .iter()
        .rposition(|&b| b == b'\n')
        .map_or(0, |i| i + 1);
    (line, offset - line_start + 1)
}

#[test]
fn includes_are_pure_ascii() {
    for path in includes() {
        let bytes = read(&path);
        if let Some(offset) = bytes.iter().position(|&b| !b.is_ascii()) {
            let (line, column) = position(&bytes, offset);
            panic!(
                "{}:{line}:{column}: non-ASCII byte 0x{:02X}. The Pawn compiler does not \
                 decode UTF-8; use plain ASCII (e.g. `-` instead of an em dash, `\"` instead \
                 of curly quotes).",
                path.display(),
                bytes[offset],
            );
        }
    }
}

#[test]
fn includes_have_no_bom() {
    for path in includes() {
        let bytes = read(&path);
        assert!(
            !bytes.starts_with(&[0xEF, 0xBB, 0xBF]),
            "{}: starts with a UTF-8 BOM. The Pawn compiler does not strip it and will \
             choke on the first directive.",
            path.display(),
        );
    }
}

#[test]
fn includes_have_no_stray_control_characters() {
    for path in includes() {
        let bytes = read(&path);
        // Tab and newline are legitimate; everything else below 0x20 (plus DEL)
        // is invisible in an editor and meaningless to the compiler.
        if let Some(offset) = bytes
            .iter()
            .position(|&b| (b.is_ascii_control() && b != b'\t' && b != b'\n') || b == 0x7F)
        {
            let (line, column) = position(&bytes, offset);
            panic!(
                "{}:{line}:{column}: stray control byte 0x{:02X}. Expected LF line endings \
                 and no CR, NUL or other control characters.",
                path.display(),
                bytes[offset],
            );
        }
    }
}

#[test]
fn generated_include_matches_the_template() {
    // The guard is only meaningful if the generated file is current: a stale
    // `.inc` could pass while the template it came from already regressed.
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let template = String::from_utf8(read(&root.join("include/mysql_samp.inc.in")))
        .expect("the template must be valid UTF-8");
    let generated = String::from_utf8(read(&root.join("include/mysql_samp.inc")))
        .expect("the generated include must be valid UTF-8");

    assert_eq!(
        template.replace("{{VERSION}}", env!("CARGO_PKG_VERSION")),
        generated,
        "include/mysql_samp.inc is out of date with include/mysql_samp.inc.in. \
         Run `cargo build` to regenerate it.",
    );
}
